name: "atlas_service"
version: "build_main"
authors:
- name: "Dorien Roosen"
  roles:
  - "author"
  - "maintainer"
  info:
    role: "Core Team Member"
    links:
      email: "dorien@data-intuitive.com"
      github: "dorien-er"
      linkedin: "dorien-roosen"
    organizations:
    - name: "Data Intuitive"
      href: "https://www.data-intuitive.com"
      role: "Data Scientist"
- name: "Weiwei Schultz"
  roles:
  - "contributor"
  info:
    role: "Contributor"
    organizations:
    - name: "Janssen R&D US"
      role: "Associate Director Data Sciences"
argument_groups:
- name: "Input (query) data arguments"
  description: "The input query dataset(s) to be annotated"
  arguments:
  - type: "string"
    name: "--id"
    description: "ID of the sample."
    info: null
    example:
    - "foo"
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--input"
    description: "Input query dataset(s) to be annotated"
    info: null
    example:
    - "input.h5mu"
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--modality"
    description: "Modality to be processed. Should match the modality in the --reference\
      \ dataset, if provided."
    info: null
    default:
    - "rna"
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--input_layer"
    description: "The layer in the input data containing the raw counts, if .X is\
      \ not to be used."
    info: null
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--input_var_gene_names"
    description: "The name of the adata var column containing gene names; when no\
      \ gene_name_layer is provided, the var index will be used.\n"
    info: null
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
- name: "Reference data arguments"
  description: "Dataset to be used as a reference for label transfer and to train\
    \ annotation algorithms on."
  arguments:
  - type: "file"
    name: "--reference"
    description: "The reference dataset to be used as a reference mapper and to train\
      \ annotation algorithms on.\n"
    info: null
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--reference_layer_raw_counts"
    description: "The layer in the reference dataset containing the raw counts, if\
      \ .X is not to be used."
    info: null
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--reference_layer_lognormalized_counts"
    description: "The layer in the reference dataset containing the log-normalized\
      \ counts."
    info: null
    default:
    - "log_normalized"
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--reference_var_gene_names"
    description: "The name of the adata .var column containing gene names if the .var\
      \ index is not to be used.\n"
    info: null
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--reference_obs_batch"
    description: "The .obs column of the reference dataset containing the batch information.\n"
    info: null
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--reference_obs_label"
    description: "The `.obs` key of the target labels to tranfer."
    info: null
    example:
    - "cell_type"
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
- name: "Annotation methods"
  description: "The available annotation methods to annotate the query dataset(s)\
    \ with."
  arguments:
  - type: "string"
    name: "--annotation_methods"
    info: null
    example:
    - "harmony_knn"
    default:
    - "scgpt_annotation"
    required: false
    choices:
    - "harmony_knn"
    - "scgpt_annotation"
    direction: "input"
    multiple: true
    multiple_sep: ";"
- name: "Pre-processing options: RNA filtering"
  description: "Pre-processing options for filtering RNA data"
  arguments:
  - type: "integer"
    name: "--rna_min_counts"
    description: "Minimum number of counts captured per cell."
    info: null
    example:
    - 200
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "integer"
    name: "--rna_max_counts"
    description: "Maximum number of counts captured per cell."
    info: null
    example:
    - 5000000
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "integer"
    name: "--rna_min_genes_per_cell"
    description: "Minimum of non-zero values per cell."
    info: null
    example:
    - 200
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "integer"
    name: "--rna_max_genes_per_cell"
    description: "Maximum of non-zero values per cell."
    info: null
    example:
    - 1500000
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "integer"
    name: "--rna_min_cells_per_gene"
    description: "Minimum of non-zero values per gene."
    info: null
    example:
    - 3
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "double"
    name: "--rna_min_fraction_mito"
    description: "Minimum fraction of UMIs that are mitochondrial."
    info: null
    example:
    - 0.0
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "double"
    name: "--rna_max_fraction_mito"
    description: "Maximum fraction of UMIs that are mitochondrial."
    info: null
    example:
    - 0.2
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
- name: "Pre-processing options: Highly variable features detection"
  description: "Pre-processing options for detecting highly variable features"
  arguments:
  - type: "integer"
    name: "--top_n_vars"
    description: "Number of top vars to be used to calculate cumulative proportions.\n\
      If not specified, proportions are not calculated. `--top_n_vars 20,50` finds\n\
      cumulative proportion to the 20th and 50th most expressed vars.\n"
    info: null
    default:
    - 50
    - 100
    - 200
    - 500
    required: false
    direction: "input"
    multiple: true
    multiple_sep: ","
  - type: "string"
    name: "--highly_variable_features_var_output"
    alternatives:
    - "--filter_with_hvg_var_output"
    description: "In which .var slot to store a boolean array corresponding to the\
      \ highly variable genes."
    info: null
    default:
    - "filter_with_hvg"
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--highly_variable_features_obs_batch_key"
    alternatives:
    - "--filter_with_hvg_obs_batch_key"
    description: "If specified, highly-variable genes are selected within each batch\
      \ separately and merged. This simple \nprocess avoids the selection of batch-specific\
      \ genes and acts as a lightweight batch correction method.\n"
    info: null
    default:
    - "sample_id"
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
- name: "Pre-processing options: Mitochondrial Gene Detection"
  description: "Pre-processing options for detecting mitochondrial genes"
  arguments:
  - type: "string"
    name: "--var_name_mitochondrial_genes"
    description: "In which .var slot to store a boolean array corresponding the mitochondrial\
      \ genes.\n"
    info: null
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--obs_name_mitochondrial_fraction"
    description: "When specified, write the fraction of counts originating from mitochondrial\
      \ genes \n(based on --mitochondrial_gene_regex) to an .obs column with the specified\
      \ name.\nRequires --var_name_mitochondrial_genes.\n"
    info: null
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--mitochondrial_gene_regex"
    description: "Regex string that identifies mitochondrial genes from --var_gene_names.\n\
      By default will detect human and mouse mitochondrial genes from a gene symbol.\n"
    info: null
    default:
    - "^[mM][tT]-"
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
- name: "Pre-processing options: QC metrics calculation options"
  description: "Pre-processing options for calculating QC metrics"
  arguments:
  - type: "string"
    name: "--var_qc_metrics"
    description: "Keys to select a boolean (containing only True or False) column\
      \ from .var.\nFor each cell, calculate the proportion of total values for genes\
      \ which are labeled 'True', \ncompared to the total sum of the values for all\
      \ genes. Defaults to the combined values specified for\n--var_name_mitochondrial_genes\
      \ and --highly_variable_features_var_output.\n"
    info: null
    example:
    - "ercc,highly_variable"
    required: false
    direction: "input"
    multiple: true
    multiple_sep: ","
- name: "Harmony integration options"
  description: "Specifications for harmony integration. Only relevant for annotation\
    \ method 'harmony_knn'."
  arguments:
  - type: "double"
    name: "--harmony_theta"
    description: "Diversity clustering penalty parameter. Specify for each variable\
      \ in group.by.vars. \ntheta=0 does not encourage any diversity. Larger values\
      \ of theta\nresult in more diverse clusters.\"\n"
    info: null
    example:
    - 0.0
    - 1.0
    - 2.0
    default:
    - 2.0
    required: false
    direction: "input"
    multiple: true
    multiple_sep: ";"
- name: "scGPT reference model"
  description: "scGPT model input, required for scGPT annotation methods"
  arguments:
  - type: "file"
    name: "--scgpt_model"
    description: "The model file containing checkpoints and cell type label mapper.\n"
    info: null
    example:
    - "best_model.pt"
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--scgpt_model_config"
    description: "The model configuration file. \n"
    info: null
    example:
    - "args.json"
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--scgpt_model_vocab"
    description: "Model vocabulary file directory.\n"
    info: null
    example:
    - "vocab.json"
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--scgpt_finetuned_checkpoints_key"
    description: "Key in the model file containing the pretrained checkpoints.\n"
    info: null
    default:
    - "model_state_dict"
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--scgpt_label_mapper_key"
    description: "Key in the model file containing the cell type class to label mapper\
      \ dictionary.\n"
    info: null
    default:
    - "id_to_class"
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
- name: "scGPT annotation options"
  description: "Specifications for scGPT annotation."
  arguments:
  - type: "string"
    name: "--scgpt_pad_token"
    description: "Token used for padding.\n"
    info: null
    default:
    - "<pad>"
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "integer"
    name: "--scgpt_pad_value"
    description: "The value of the padding token.\n"
    info: null
    default:
    - -2
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "integer"
    name: "--scgpt_n_hvg"
    description: "Number of highly variable genes to consider for scGPT annotation.\n"
    info: null
    default:
    - 1200
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "boolean"
    name: "--scgpt_dsbn"
    description: "Apply domain-specific batch normalization\n"
    info: null
    default:
    - true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "integer"
    name: "--scgpt_batch_size"
    description: "The batch size to be used for embedding inference.\n"
    info: null
    default:
    - 64
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "integer"
    name: "--scgpt_n_input_bins"
    description: "The number of bins to discretize the data into; When no value is\
      \ provided, data won't be binned.\n"
    info: null
    default:
    - 51
    required: false
    min: 1
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "integer"
    name: "--scgpt_seed"
    description: "Seed for random number generation used for binning. If not set,\
      \ no seed is used.\n"
    info: null
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
- name: "Outputs"
  description: "The output file to write the annotated dataset to."
  arguments:
  - type: "file"
    name: "--output"
    description: "The output file.\n"
    info: null
    example:
    - "output.h5mu"
    must_exist: true
    create_parent: true
    required: true
    direction: "output"
    multiple: false
    multiple_sep: ";"
resources:
- type: "nextflow_script"
  path: "main.nf"
  is_executable: true
  entrypoint: "run_wf"
description: "A pipeline to process and annotate gene expression data."
info: null
status: "enabled"
scope:
  image: "public"
  target: "public"
dependencies:
- name: "metadata/add_id"
  repository:
    type: "github"
    repo: "openpipelines-bio/openpipeline"
    tag: "2.0.0"
- name: "dataflow/split_h5mu"
  repository:
    type: "github"
    repo: "openpipelines-bio/openpipeline"
    tag: "2.0.0"
- name: "workflows/multiomics/process_samples"
  alias: "process_samples_workflow"
  repository:
    type: "github"
    repo: "openpipelines-bio/openpipeline"
    tag: "2.0.0"
- name: "workflows/annotation/scgpt_annotation"
  alias: "scgpt_annotation_workflow"
  repository:
    type: "github"
    repo: "openpipelines-bio/openpipeline"
    tag: "2.0.0"
repositories:
- type: "github"
  name: "openpipeline"
  repo: "openpipelines-bio/openpipeline"
  tag: "main_build"
- type: "github"
  name: "op"
  repo: "openpipelines-bio/openpipeline"
  tag: "2.0.0"
links:
  repository: "https://github.com/openpipelines-bio/openpipeline_incubator"
  docker_registry: "ghcr.io"
runners:
- type: "nextflow"
  id: "nextflow"
  directives:
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: false
    transcript: false
    publish: false
  config:
    labels:
      mem1gb: "memory = 1000000000.B"
      mem2gb: "memory = 2000000000.B"
      mem5gb: "memory = 5000000000.B"
      mem10gb: "memory = 10000000000.B"
      mem20gb: "memory = 20000000000.B"
      mem50gb: "memory = 50000000000.B"
      mem100gb: "memory = 100000000000.B"
      mem200gb: "memory = 200000000000.B"
      mem500gb: "memory = 500000000000.B"
      mem1tb: "memory = 1000000000000.B"
      mem2tb: "memory = 2000000000000.B"
      mem5tb: "memory = 5000000000000.B"
      mem10tb: "memory = 10000000000000.B"
      mem20tb: "memory = 20000000000000.B"
      mem50tb: "memory = 50000000000000.B"
      mem100tb: "memory = 100000000000000.B"
      mem200tb: "memory = 200000000000000.B"
      mem500tb: "memory = 500000000000000.B"
      mem1gib: "memory = 1073741824.B"
      mem2gib: "memory = 2147483648.B"
      mem4gib: "memory = 4294967296.B"
      mem8gib: "memory = 8589934592.B"
      mem16gib: "memory = 17179869184.B"
      mem32gib: "memory = 34359738368.B"
      mem64gib: "memory = 68719476736.B"
      mem128gib: "memory = 137438953472.B"
      mem256gib: "memory = 274877906944.B"
      mem512gib: "memory = 549755813888.B"
      mem1tib: "memory = 1099511627776.B"
      mem2tib: "memory = 2199023255552.B"
      mem4tib: "memory = 4398046511104.B"
      mem8tib: "memory = 8796093022208.B"
      mem16tib: "memory = 17592186044416.B"
      mem32tib: "memory = 35184372088832.B"
      mem64tib: "memory = 70368744177664.B"
      mem128tib: "memory = 140737488355328.B"
      mem256tib: "memory = 281474976710656.B"
      mem512tib: "memory = 562949953421312.B"
      cpu1: "cpus = 1"
      cpu2: "cpus = 2"
      cpu5: "cpus = 5"
      cpu10: "cpus = 10"
      cpu20: "cpus = 20"
      cpu50: "cpus = 50"
      cpu100: "cpus = 100"
      cpu200: "cpus = 200"
      cpu500: "cpus = 500"
      cpu1000: "cpus = 1000"
  debug: false
  container: "docker"
build_info:
  config: "src/atlas_service/config.vsh.yaml"
  runner: "nextflow"
  engine: "native"
  output: "target/nextflow/atlas_service"
  executable: "target/nextflow/atlas_service/main.nf"
  viash_version: "0.9.1"
  git_commit: "21df874fc481bb538079be5b78e553d30ca78ad2"
  git_remote: "https://github.com/openpipelines-bio/openpipeline_incubator"
  dependencies:
  - "target/dependencies/github/openpipelines-bio/openpipeline/2.0.0/nextflow/metadata/add_id"
  - "target/dependencies/github/openpipelines-bio/openpipeline/2.0.0/nextflow/dataflow/split_h5mu"
  - "target/dependencies/github/openpipelines-bio/openpipeline/2.0.0/nextflow/workflows/multiomics/process_samples"
  - "target/dependencies/github/openpipelines-bio/openpipeline/2.0.0/nextflow/workflows/annotation/scgpt_annotation"
package_config:
  name: "openpipeline_incubator"
  version: "build_main"
  info:
    test_resources:
    - type: "s3"
      path: "s3://openpipelines-bio/openpipeline_incubator/resources_test"
      dest: "resources_test"
  repositories:
  - type: "github"
    name: "openpipeline"
    repo: "openpipelines-bio/openpipeline"
    tag: "main_build"
  viash_version: "0.9.1"
  source: "src"
  target: "target"
  organization: "openpipelines-bio"
  links:
    repository: "https://github.com/openpipelines-bio/openpipeline_incubator"
    docker_registry: "ghcr.io"
