name: generate_html
namespace: ingestion_qc
description: Generate an HTML report from the QC metrics
authors: 
  - __merge__: /src/authors/jakub_majercik.yaml
    roles: [author]
  - __merge__: /src/authors/dorien_roosen.yaml
    roles: [author]
  - __merge__: /src/authors/robrecht_cannoodt.yaml
    roles: [author]
  - __merge__: /src/authors/weiwei_schultz.yaml
    roles: [contributor]
argument_groups:
  - name: Inputs
    arguments:
      - name: --input
        type: file
        required: true
        direction: input
        description: The input JSON file containing the QC metrics
        example: path/to/file.json
  - name: Outputs
    arguments:
      - name: --output
        type: file
        required: true
        direction: output
        description: The output HTML report
        example: path/to/file.html
resources:
  - type: bash_script
    path: script.sh
engines:
  - type: docker
    image: node:latest
    setup:
      - type: apt
        packages:
          - git
      - type: docker
        run: |
          npm install -g pnpm@latest-10 \
          && cd /opt && git clone https://github.com/openpipelines-bio/incubator_ingestion_qc.git \
          && cd incubator_ingestion_qc && pnpm install
runners:
  - type: executable
  - type: nextflow